FROM golang:1.19.5 as base

# source requires --login
SHELL ["/bin/bash", "--login", "-c"]

# Install Node v16
RUN apt-get update && apt upgrade -y
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
RUN source ~/.bashrc
RUN nvm install 16.16.0

RUN npm install --global yarn

# Switch shell back
SHELL ["/bin/sh", "-c"]

# Download mage
WORKDIR /home
RUN git clone https://github.com/magefile/mage
WORKDIR /home/mage
RUN go run bootstrap.go

WORKDIR /home/cosmos/tools/cosmos-web/grafana-plugins/cosmos-grafana-plugins